version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-browsers
    working_directory: ~/repo
    environment:
      DBUS_SESSION_BUS_ADDRESS: /dev/null
    steps:
      - checkout
      - run: wget http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar
      - run:
          command: java -jar selenium-server-standalone-3.4.0.jar -port 6666
          background: true
      - run: wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
      - run: unzip chromedriver_linux64.zip
      - run: sudo cp -f chromedriver /usr/local/bin/
      - run: curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: sudo dpkg -i google-chrome.deb
      - run: sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
      - run: rm google-chrome.deb
      - run:
          command: |
            echo "$FILELIST"
            mvn -B clean test -Dsurefire.suiteXmlFiles=ORAPP.xml
      - store_artifacts:
          path: ~/repo/target/surefire-reports

workflows:
  version: 2
  test:
    jobs:
      - build
